name: Ryzom Live Index

on:
  push:
    paths-ignore:
      - 'index/**'
  workflow_dispatch:

env:
  app: ryzom_live
  username: "Github Action"
  useremail: "zerotacg@users.noreply.github.com"

concurrency:
  group: "index"
  cancel-in-progress: false

jobs:
  index:
    runs-on: ubuntu-latest
    if: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch ) }}
    steps:
      - uses: actions/checkout@v4
      - name: get current index
        run: |
          ./src/patch-live-index.sh
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  to-json:
    if: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch ) }}
    needs: [index]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/zerotacg/ryzom-patch-info:latest
      volumes:
        - ${{ github.workspace }}:/app
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
      - run: |
          find .
          ryzom-patch-info --index-file ryzom.idx > ${{ env.app }}.json
          find .
          cat *.json
      - uses: actions/upload-artifact@v4
        with:
          name: index
          path: ${{ env.app }}.json

  push:
    if: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch ) }}
    needs: [to-json]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: index
          merge-multiple: true
      - name: get current index
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          find .
          git config --global user.name '${{ env.username }}'
          git config --global user.email '${{ env.useremail }}'
          git commit -am "[ci] Update Index" || true
          git push
